### ISSUE TITLE
examples/ingersoll.py normals

### ISSUE THREAD

**Issue by nschorgh** [sampotter/python-flux#17]
Somehow `shape_model.N` in the program and `shape_model.N` in `FF.bin` are not the same. 
I haven't pinpointed the reason yet, but the normals in `FF.bin` are not normalized.
The other variables, `V`, `F`, `P`, and `A`, are identical.

```
FF2 = CompressedFormFactorMatrix.from_file('FF.bin')   
shape_model2 = FF2.shape_model
print(min(shape_model.N[:,2] - shape_model2.N[:,2]))
```

**Comment by sampotter** [comment]
This should be fixed in 9cdd1b215fc294de82ae70c52bb4f1c905fb9ef3. Once you have a chance to check that it works for you, too, let me know and I'll close this out (I think you can also close out issues yourself, too... can't remember).
