### ISSUE TITLE
Add support for conductionQ

### ISSUE THREAD

**Issue by sampotter** [sampotter/python-flux#2]

**Comment by steo85it** [comment]
Is it correct that this step would require computing `dT/dz` via the conductionQ C library you already imported, then including it in `flux/model.py` such that (with some simplifications):
```
    # solve IR section for each time step sequentially
    T = []
    for B in B_arr.T:
        if clamp:
            B = np.maximum(0, B)
        IR = FF@((1 - rho)*B) # + FF@dT/dz (eq.9)
        Q = solve_radiosity(FF, IR)[0]
        if clamp:
            Q = np.maximum(0, Q)
        T.append((((1 - rho)*B + emiss*Q)/(emiss*sigma))**0.25) # + FF@dT/dz (eq.1)
```
?

Yesterday I was cross-checking code and equations on overleaf (might be a good idea to add references to the Eqs within the code, once the manuscript is "more stable"), to understand "what's missing" to make the whole results more "physical".

**Comment by sampotter** [comment]
Yep, that's right, except dT/dz should be replaced k*(dT/dz).

Quick explanation for `PccThermalModel1D`:

```cython
cdef class PccThermalModel1D:
    cdef:
        int nfaces
        int nz
        double t, emissivity
        double[::1] z
        double[::1] ti
        double[::1] rhoc
        double[::1] Qprev
        double[::1] Fsurf
        double[:, ::1] T
```

The idea here is that this is exactly _all_ of the 1D thermal models for each face in the triangle mesh (hence, `nfaces`). The variable `nz` is just the number of points in z direction. Variable `t` is the current time, and `emissivity` is just constant over the entire shape model (can make this a vector easily). Then, `z` stores the actually depths, and `ti` and `rhoc` are the thermal inertia and volumetric heat capacity at each depth level (again, constant over each face---can change that to make them variable). The vector `Qprev` stores the irradiance at the previous time step, and `Fsurf` is actually the computed heat flux---so this is your k*(dT/dz). Lastly, `T` is an `nfaces` x `nz + 1` array containing the temperature at each z slice.

I haven't tested this wrapper carefully yet. One thing that's a little annoying is that Norbert and I use different indexing conventions. I would compare my indices with his C code [here](https://github.com/sampotter/python-flux/blob/master/flux/pcc/conductionQ.c), I think because when he wrote his C port of [the original Fortran version](https://github.com/nschorgh/Planetary-Code-Collection/blob/master/Common/conductionQ.f90), he wanted to preserve the 1-style indexing.

Also helpful for debugging is the [user guide](https://github.com/nschorgh/Planetary-Code-Collection/blob/master/UserGuide.pdf) for his [Planetary Code Collection](https://github.com/nschorgh/Planetary-Code-Collection).

But yeah, if I got lucky ;-) everything just work and it should be easy to hook this up. If you want to try to do this yourself, I'm happy to help; otherwise I will have time to finish this soon (truly).

**Comment by steo85it** [comment]
Thanks for the explanation! (and wow, he wrote a full guide for his codes, remarkable ^^ wish I was as methodic)
We'll see, depending on inspiration, I'll let you know if I try (and probably get stuck) but mainly wanted to check and write down some initial thoughts before forgetting. :)

**Comment by steo85it** [comment]
Hi Sam,
I got back to this after some weeks spent on a proposal, and I tested your `conductionQ` wrapper (on 1 tile). Generally speaking, it works and I get reasonable values when compared to the original Fortran code.
Still, there are some differences, not sure if due to my understanding or to residual issues. Let me paste here the results of some tests and their setup (at the end a short summary of what I noticed).

I ran `testcrankQ.f90` from `Planetary-Code-Collection/Common`, reducing `nz=3` and n_steps `n=0,3` 
```
 Skin depth=   0.54389917978230473     
 Time step=   495661.76666666666     
 zmax=   2.5000000000000000     
 Thermal inertia=   120.00000000000000       Period=   59479412.000000000     
 Heat Flux at bottom boundary= -0.20000000298023224     
================ INPUT TO STEP 0
 t   495661.76666666666  
 nz           3
 z  0.49019608759779254        1.4705882627933775        2.5000000000000000     
 dt   495661.76666666666     
 Qn   470.84688077122127     
 Qnp1   470.20160144930207     <== WHERE DOES THIS COME FROM?
 T   210.00000000000000        210.00000000000000        210.00000000000000     
 ti   120.00000000000000        120.00000000000000        120.00000000000000     
 rhocv   960000.00000000000        960000.00000000000        960000.00000000000     
 emiss   1.0000000000000000     
================
 bef     step      0
================
 Tsurf   210.00000000000000     
 Fgeo  0.20000000298023224        <==== IS THIS SET IN THE PYTHON WRAP?
 Fsurf   2.0738049756921318E-317
 rhoc   960000.00000000000        960000.00000000000        960000.00000000000     
 k   6.9000266971681809E-310   6.9000266971681809E-310   0.0000000000000000     
 beta   0.0000000000000000     
 alpha   6.9000266971681809E-310   6.9000266971681809E-310   0.0000000000000000     
 gamma   6.9000266971681809E-310   6.9000266971681809E-310   0.0000000000000000     
 a   6.9000266972527649E-310   6.9000266972527649E-310   4.0517098332638943E-317
 b   6.9000266971681809E-310   6.9000266971681809E-310   0.0000000000000000     
 c   6.9000266971681809E-310   6.9000266971681809E-310   0.0000000000000000 
======    
 aft step 0
=================
 Tsurf   303.36763239572173     
 Qn   470.20160144930207     
 Fsurf   2.8115281235962448     
== INPUT TO STEP 1
 t   991323.53333333333 
 nz           3
 z  0.49019608759779254        1.4705882627933775        2.5000000000000000     
 dt   495661.76666666666     
 Qn   470.20160144930207     
 Qnp1   468.26753214941181      <===== NOT CLEAR IF THIS IS INPUT OR OUTPUT
 T   211.48762663851892        210.00617401685054        210.09996975232275     
 ti   120.00000000000000        120.00000000000000        120.00000000000000     
 rhocv   960000.00000000000        960000.00000000000        960000.00000000000     
 emiss   1.0000000000000000
==================     
 bef step          1
==================
 Tsurf   303.36763239572173     
 Fgeo  0.20000000298023224     
 Fsurf   2.8115281235962448     
 rhoc   960000.00000000000        960000.00000000000        960000.00000000000     
 k   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 beta   6.9000271923642983E-310
 alpha   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 gamma   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 a   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 b   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 c   0.0000000000000000        0.0000000000000000        0.0000000000000000  
====== 
 aft step 1
=====================
 **Tsurf   301.04546359762196
 Qn   468.26753214941181     
 Fsurf   2.6971202452851495**
=====================     
 # Depth           Temperature         Heat_Flux
  **0.49019608759779254        212.90427746298337        0.0000000000000000     
   1.4705882627933775        210.02432280747988       -0.0000000000000000     
   2.5000000000000000        210.19930009541665       -0.0000000000000000**
```
then I ran a small test calling for the wrapper  and setting the same input
```
import numpy as np
from flux.thermal import PccThermalModel1D

model = PccThermalModel1D(nfaces=1,z=np.array([0.49019608759779254,1.4705882627933775,2.5]),T0=210.,ti=120.,rhoc=960000.,emissivity=1.)

Qprev = np.array([470.84688077122127])
for i in range(2):
    model.step(i*495661.76666666666,Qprev)
    Qprev = model.Qprev
```
which, when adding some printouts, gives
```
=== INPUT FOR STEP 0
t 0.0
Qprev [0.]
T [[210. 210. 210. 210.]]
Fsurf [0.]
========
step 0
========
rhoc[0] = 6.9197e-310
rhoc[1] = 960000
rhoc[2] = 960000
rhoc[3] = 960000
k[0] = 6.95333e-310
k[1] = 0.015
k[2] = 0.015
k[3] = 0.015
beta = 0.268587
alpha[0] = 7.90505e-323
alpha[1] = 0.0040288
alpha[2] = 0.00374337
alpha[3] = 6.9197e-310
gamma[0] = 6.9197e-310
gamma[1] = 0.0040288
gamma[2] = 0.00393054
gamma[3] = 0.00365424
a[0] = 3.95253e-323
a[1] = -0.0040288
a[2] = -0.00393054
a[3] = -0.00365424
b[0] = 6.91969e-310
b[1] = 1.00806
b[2] = 1.00767
b[3] = 1.00365
c[0] = 6.95333e-310
c[1] = -0.0040288
c[2] = -0.00374337
c[3] = -6.9197e-310
lbpredcorr:
Told[0] = 6.95314e-310
Told[1] = 210
Told[2] = 210
Told[3] = 210
r[0] = 0
r[1] = 212.614
r[2] = 210
r[3] = 210
T[0] = 210
T[1] = 210.935
T[2] = 210.004
T[3] = 210
lbpredcorr:
Told[0] = 6.95314e-310
Told[1] = 210
Told[2] = 210
Told[3] = 210
r[0] = 0
r[1] = 212.448
r[2] = 210
r[3] = 210
T[0] = 379.204
T[1] = 210.757
T[2] = 210.003
T[3] = 210
==== RESULTS OF STEP 0 (AND INPUT OF STEP 1?)
t 495661.76666666666
Qprev [470.84688077]
T [[303.4659563  210.75714431 210.00295336 210.00001075]]
Fsurf [2.83688959]
==== 
step 1 495661.76666666666
== inside conductionQ
rhoc[0] = 6.9197e-310
rhoc[1] = 960000
rhoc[2] = 960000
rhoc[3] = 960000
k[0] = 6.95333e-310
k[1] = 0.015
k[2] = 0.015
k[3] = 0.015
beta = 0.268587
alpha[0] = 7.90505e-323
alpha[1] = 0.0040288
alpha[2] = 0.00374337
alpha[3] = 6.9197e-310
gamma[0] = 6.9197e-310
gamma[1] = 0.0040288
gamma[2] = 0.00393054
gamma[3] = 0.00365424
a[0] = 3.95253e-323
a[1] = -0.0040288
a[2] = -0.00393054
a[3] = -0.00365424
b[0] = 6.9197e-310
b[1] = 1.00806
b[2] = 1.00767
b[3] = 1.00365
c[0] = 6.95333e-310
c[1] = -0.0040288
c[2] = -0.00374337
c[3] = -6.9197e-310
lbpredcorr:
Told[0] = 6.95333e-310
Told[1] = 210.757
Told[2] = 210.003
Told[3] = 210
r[0] = 0
r[1] = 213.906
r[2] = 210.006
r[3] = 210
T[0] = 303.466
T[1] = 212.195
T[2] = 210.014
T[3] = 210
==== RESULTS OF STEP 1
**t 991323.5333333333
Qprev [470.84688077]
T [[301.44931277 212.19519964 210.01442462 210.00007395]]
Fsurf [2.73117581]**
```
I noticed a couple of things:
1. the value of Qprev is not updated by `model.step()`. I also tried to manually introduce Q values from the fortran run, but I still get different results + that's not what should happen, I think.
2. `Fgeotherm` value seems to be set to 0 in the python code for `model.step()`, while different from it in the Fortran run (reasonably, I'd say). Even when updating the value, I get different output.
3. When setting `nz=3`, one gets a 4-dim output in python (the [0] element being the surface) and only the 3 sub-surface layers in Fortran. Surface values are there, clearly, I'm just wondering if I'm introducing some difference that would make results non comparable.

Do you think there is something wrong here? Or just my way of advancing time steps? (I hope including all this output is useful rather than messy ^^) Let me know if some different info/test would be useful to pinpoint issues.

**Comment by steo85it** [comment]
Ok, after understanding things a bit better, I tested `conductionQ` inside `ingersoll.py` by adding a second call to `compute_steady_state()`
```
# set-up the thermal model (only once) - suppose 3 layers, to test
model = PccThermalModel1D(nfaces=E.shape[0], z=np.array([0.49019608759779254, 1.4705882627933775, 2.5]), T0=210., ti=120., rhoc=960000., emissivity=1.)
dt = 495661.76666666666 # seconds (should be the general time step)
# normal call to get T w/o subsurface heat flux
T = compute_steady_state_temp(FF, E, args.rho, args.emiss,Fsurf=0.)
# get irradiance at step and compute k dT/dz
Qnp1 = sigma*args.emiss*(T**4.)
model.step(dt, Qnp1.astype('double'))
# second call to update T including subsurface heat flux
T2 = compute_steady_state_temp(FF, E, args.rho, args.emiss,Fsurf=model.Fsurf)
```
where I modified `compute_steady_state_temp` to include H=k dT/dz (the heat flux in the paper)
```
def compute_steady_state_temp(FF, E, rho, emiss, Fsurf=0.,
                              clamp=True, tol=np.finfo(np.float64).eps):
    if E.ndim == 1:
        B = solve_radiosity(FF, E, rho)[0]
        if clamp:
            B = np.maximum(0, B)
        IR = FF@((1 - rho)*B + Fsurf)
        Q = solve_radiosity(FF, IR)[0]
        if clamp:
            Q = np.maximum(0, Q)
        return (((1 - rho)*B + emiss*Q + Fsurf)/(emiss*sigma))**0.25
    ...
```
Does it look reasonable? Results are "ok" (have to figure out a reliable comparison, besides the one above), I don't really like recomputing `Qnp1 = sigma*args.emiss*(T**4.)` from `compute_steady_state_temp` output, but I prefer passing `Fsurf` as parameter instead of `model` (which would allow to compute the time step directly inside the function).
Here is the difference T2 (with subsurf flux) - T:
![image](https://user-images.githubusercontent.com/29377066/110396328-d9c72700-803d-11eb-9547-e06150e545e4.png)
and T, for comparison
![image](https://user-images.githubusercontent.com/29377066/110396367-eba8ca00-803d-11eb-895c-33c4093267cd.png)

**Comment by sampotter** [comment]
Thanks for the posts, I'm working my way through them...

Here is one quick update: you were right about Fgeotherm being inactive in the Python wrapper. I never set this to anything other than zero, so hadn't gotten around to that yet. But it's easy to do, so I went ahead and did it in 7036cc8479066f48fd4ba1840055fa1d3fc048aa. All the changes are in thermal.pyx. BTW, the funny "pyx" extension is for a [Cython](https://cython.readthedocs.io/en/latest/) extension file. It's basically typed Python that gets compiled to C, which is a language to use to optimize slow Python code and also to wrap C libraries. (E.g., that python-embree package I wrote is really just one big Cython file.)

Let me know if Fgeotherm works OK for you as I check the rest of what you sent...

One thing that occurred to me is that we should probably close this issue when we "know that conductionQ works"---I'm not totally sure what a good test for that would be. But this package is missing tests right now, and those need to be added. So maybe we can try to brainstorm a good "unit test" for conductionQ.

**Comment by steo85it** [comment]
Hi Sam! Thanks, I'll check that later today! And yes, I never used cython before but I figured out how to modify, compile, etc... to test. ;)
About the unittests, good idea: we could reproduce Norbert's test (I used the Fortran one to check my use of the routines), simulate the input and set a check on the output of the conductionQ call.
It's always convenient to have such tests.

**Comment by sampotter** [comment]
Perfect :-)

I didn't realize Norbert had some test for conductionQ... where is it...?

**Comment by steo85it** [comment]
Well, I call them "tests" but it's more like examples since there is no template output to compare with... anyway, I meant, e.g.,
testcrankQ.f90 from Planetary-Code-Collection/Common/Tests (by memory).

**Comment by nschorgh** [comment]
In my C-version of conductionQ, `z[1]` is the first grid point below the surface and `z[0]=0`. 
Arrays `z` and `T` are of length `nz+1`, and `T[0]` is the surface temperature (called `Tsurf` in the Fortran version).

I could write a Python version of conductionQ, but it will degrade performance.

The C and Fortran version use the same input parameters, so Test/Tprofile_testcrankQ, produced by the Fortran version, should be the same as Tprofile produced by the C version, although I see one of the twelve lines of output differs by a tiny bit.

**Comment by steo85it** [comment]
Ah, this is even better: I just checked the Fortran version (I'm much more accustomed to Fortran than C) and simply thought of using its output as template.

**Comment by nschorgh** [comment]
Please do use setgrid, because there is one specific restriction for the vertical grid spacing, namely z(2) = 3*z(1), which setgrid takes care of.

**Comment by steo85it** [comment]
I just set up a small (very drafty) pull request for a unittest for conductionQ in PR https://github.com/sampotter/python-flux/pull/19#issue-594214794 (it also includes a python version of `setgrid`, as discussed)
