### ISSUE TITLE
wrong illumination geometry in debug-compressed-form-factor-matrix

### ISSUE THREAD

**Issue by steo85it** [sampotter/python-flux#40]
I think `debug-compressed-form-factor-matrix` branch has an issue similar to #4 . 
When running [haworth.py](https://github.com/sampotter/python-flux/blob/master/examples/haworth.py) from that branch, I get the left result in the figure below (E, above; T, below) - on the other hand, when I run the same experiment from a9f3dc13 , I get the result on the right. The latter makes more sense, considering the shape of the crater and shadowed areas therein.

![immagine](https://user-images.githubusercontent.com/29377066/146586868-656c9498-b46d-472d-b286-b7185d6f411d.png)
![immagine](https://user-images.githubusercontent.com/29377066/146586905-b06dfb8b-8e4e-402d-8fcf-099a4c8b9a65.png)

I checked and the issue which solved #4 still looks "solved": now that I know that the problem doesn't come from my own code/meshes/changes, I will try to track it down checking differences among the commits. 
Ah, this happens with both embree or CGAL: it has to be related to some of the clean-ups, but not to this "fundamental change". Also, I went back in history in the master branch only to avoid having to debug unrelated errors in the haworth.py test, not because the issue showed up (I'll check now at which point it appears in master, if any).

@sampotter

**Comment by nschorgh** [comment]
For a (x,y,z) mesh there is no fundamental way to decide what is inside or outside, so the choice whether N[:,2]>0, N[:,2]<0, or N=radial counts as outside has to be made manually.

**Comment by steo85it** [comment]
Yes, but in the given example the mesh was the same (and derived from stereo projected values...) and we still get very inconsistent results. I'm fine with providing the correct N, but I'd like the code to treat it consistently.

**Comment by steo85it** [comment]
Ok, I verified that the latest revision of the master branch still gives consistent results with the "expected behaviour"

**Comment by sampotter** [comment]
Well, this definitely looks like a bug in how to decide the direction of the surface normal (should be directed outward), or possibly the sun direction vector (should be directed from the triangle to the sun).

This looks like a bug in haworth.py, i.e. user error in the script, not a bug in the library itself...

**Comment by steo85it** [comment]
Unless I lost track of things, I've been running the same identical version of haworth.py with those 2 commits, and I only get the correct result with one of them.

**Comment by sampotter** [comment]
Understood. I'll take a close look at these commits and figure out what happened.

**Comment by sampotter** [comment]
Okay, I think I fixed this. It was a stupid mistake. I forgot to negate the result of `is_occluded` in `TrimeshShapeModel.get_direct_irradiance`. See https://github.com/sampotter/python-flux/commit/2e4d8c8781aa22c0cc714f39aca8ee9e9afe676d. Here's what I get from Haworth:

![haworth_E](https://user-images.githubusercontent.com/6035363/146973659-fa6cc9f7-d221-4ea7-b044-6d9ab9f1fb4a.png)
![haworth_T](https://user-images.githubusercontent.com/6035363/146973682-d2157bf2-dc9a-4a45-ab35-6d9134bab853.png)
![haworth_T_shadow](https://user-images.githubusercontent.com/6035363/146973693-33575c9d-2f24-4259-880d-87fad78b1d69.png)

**Comment by steo85it** [comment]
Yay, this looks great! Thanks for finalizing the search and solving it. It looks solved on my side, too.
