### ISSUE TITLE
Failure to build wheels for embree

### ISSUE THREAD

**Issue by ivyyye** [sampotter/python-flux#71]
Hi Sam! or anyone who can help!

I'm using WSL and am trying to clone your fast radiocity in python repository to my virtual environment. I've successfully made and activated it, and when performing the third line, python setup.py install, I get warnings that setup.py is deprecated, so inside of my python-embree I have simply done, python install ., and get a failure to build wheels for embree. 

I have updated cython, setuptools, GCC, python3.10, cmake, and have cleared my pips cache before trying again, but no matter what I get this error. 
<img width="946" alt="radiocityerror" src="https://github.com/user-attachments/assets/2caac435-c244-4783-80a4-ebd6e989c705" />

Any suggestions? Thanks in advance!!

**Comment by sampotter** [comment]
@ivyyye thanks for making this issue.

This is actually to do with a separate repository of mine, [python-embree](https://github.com/sampotter/python-embree). I'm going to close this. Would you mind re-opening this issue over on that repo? And then we can start looking into debugging it...
